# configuration file for TravisCI

language: java

jdk:
  - oraclejdk8

# install java8
addons:
  apt:
    packages:
      - oracle-java8-installer

cache:
  apt: true
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

# only build master
branches:
    only:
    - master
    - gui-test

# container-based build:
sudo: false

#build project, verify and execute sonar
install:
  - mvn install verify sonar:sonar -Dmaven.javadoc.skip=true -B

# report coverage to codacy
script:
  - curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar >jpm4j.jar
  - java -jar jpm4j.jar -u init
  - /home/travis/jpm/bin/jpm install com.codacy:codacy-coverage-reporter:assembly
  - /home/travis/jpm/bin/codacy-coverage-reporter -l Java -r target/site/jacoco/jacoco.xml
