# configuration file for TravisCI

# Notes:
#  - you can skip a build by adding [ci skip] to the commit message
#

# see http://about.travis-ci.org/docs/user/languages/java/
language: java

# test for these JDK versions and environments
jdk:
#   - oraclejdk7
   - oraclejdk8

env:
   - GITHUB_TOKEN=GITHUB_TOKEN

addons:
  apt:
    packages:
      - oracle-java8-installer


# only build these branches (RegEx is also valid, eg. /^deploy.*$/):
branches:
    only:
    - master
    - /v\d+\.\d+[a-z]/

# container-based build:
sudo: false

# Run Integration tests
script:
  - mvn verify
  - mvn clean install sonar:sonar

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-v0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$GITHUB_TOKEN@github.com/nappydevelopment/Nappy-the-ingenious --tags

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - "jar/nappy-the-ingenious-0.0.1-SNAPSHOT.jar"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true

# record coverage to codacy
after_success:
  - curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar >jpm4j.jar
  - java -jar jpm4j.jar -u init
  - /home/travis/jpm/bin/jpm install com.codacy:codacy-coverage-reporter:assembly
  - /home/travis/jpm/bin/codacy-coverage-reporter -l Java -r target/site/jacoco/jacoco.xml