# configuration file for TravisCI

# Notes:
#  - you can skip a build by adding [ci skip] to the commit message
#

# see http://about.travis-ci.org/docs/user/languages/java/
language: java

# test for these JDK versions and environments
jdk:
#   - oraclejdk7
   - oraclejdk8

env:
   - GITHUB_TOKEN=GITHUB_TOKEN

addons:
  apt:
    packages:
      - oracle-java8-installer


# only build these branches (RegEx is also valid, eg. /^deploy.*$/):
branches:
    only:
    - master
    - travis-test
    - /v\d+\.\d+[a-z]/

# container-based build:
sudo: false

# Run Integration tests
script:
  - mvn clean install verify sonar:sonar

# record coverage to codacy
after_success:
  - curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar >jpm4j.jar
  - java -jar jpm4j.jar -u init
  - /home/travis/jpm/bin/jpm install com.codacy:codacy-coverage-reporter:assembly
  - /home/travis/jpm/bin/codacy-coverage-reporter -l Java -r target/site/jacoco/jacoco.xml
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - git status
  - git checkout $TRAVIS_BRANCH
  - git status
  - export GIT_TAG=$TRAVIS_BRANCH-v0.1.$TRAVIS_BUILD_NUMBER
  - git add -f jar/*.jar
  - git commit -m "Generated from TravisCI $GIT_TAG [ci skip]"
  - git status
  - git --no-pager log | head
# - git push -q https://$GITHUB_TOKEN@github.com/nappydevelopment/Nappy-the-ingenious --tags
