DROP TABLE IF EXISTS Simpsons;
CREATE TABLE Simpsons( ID INT, name VARCHAR, nickname VARCHAR, description_en VARCHAR, description_de VARCHAR, male BOOL, human BOOL, alive BOOL, simpson BOOL, age VARCHAR, job VARCHAR, famous BOOL, skincolor VARCHAR, haircolor VARCHAR, religous BOOL, smokes BOOL, homosexual BOOL, american BOOL, married BOOL, character VARCHAR, moes_bar BOOL, fat BOOL, wearings VARCHAR);
Insert Into simpsons Values
(01,'Eleanor Abernathy','Katzenfrau',null,null,false,true,true,false,'adult',null,false,'yellow','grey',false,true,false,true,false,'crazy',false,false,null),
(02,'Martha Quimby',null,null,null,false,true,true,false,'adult','major',false,'yellow','black',false,false,false,true,true,'sane',false,false,'hat'),
(03,'Luann van Houten',null,null,null,false,true,true,false,'adult','firefighter',false,'yellow','blue',false,false,true,false,true,'sane',false,false,'glasses'),
(04,'Brandine Spuckler',null,null,null,false,true,true,false,'adult','mascot',false,'yellow','orange',false,true,false,true,true,'crazy',false,false,null),
(05,'Helen Lovejoy',null,null,null,false,true,true,false,'adult','church',false,'yellow','grey',true,false,false,true,true,'gossip',false,false,null),
(06,'Bernice Hibbert',null,null,null,false,true,true,false,'adult','wife',false,'dark','black',false,false,false,true,true,'alcoholic',false,false,'necklace'),
(07,'Manjula Nahasapeemapetilon',null,null,null,false,true,true,false,'adult','wife',false,'dark','black',false,false,false,false,true,'sane',true,false,null),
(08,'Elizabeth Hoover',null,null,null,false,true,true,false,'adult','school',false,'yellow','brown',false,true,false,true,false,'frustrated',false,false,'glasses'),
(09,'Doris Peterson','Friedman',null,null,false,true,true,false,'adult','school',false,'yellow','brown',false,true,false,true,false,'grumpy',false,true,null),
(10,'Edna Krabappel',null,null,null,false,true,false,false,'adult','school',false,'yellow','brown',false,true,false,true,true,'grumpy',true,false,null),
(11,'Judith Underdunk',null,null,null,false,true,true,false,'adult','wife',true,'yellow','grey',false,false,false,false,true,'evil',false,false,'necklace'),
(12,'Agnes Skinner',null,null,null,false,true,true,false,'old','pensioner',false,'yellow','grey',false,false,false,true,false,'temperament',false,false,'wig'),
(13,'Patty Bouvier',null,null,null,false,true,true,true,'adult','driving license office',false,'yellow','blue',false,true,true,true,false,'grumpy',false,true,'necklace'),
(14,'Selma Bouvier',null,null,null,false,true,true,true,'adult','driving license office',false,'yellow','blue',false,true,false,true,false,'grumpy',false,true,'necklace'),
(15,'Marge Simpson',null,null,null,false,true,true,true,'adult','wife',false,'yellow','blue',true,false,false,true,true,'sane',false,false,'necklace'),
(16,'Jacqueline Bouvier','Jackie',null,null,false,true,true,true,'old','pensioner',false,'yellow','grey',false,true,false,true,false,'sane',false,false,'necklace'),
(17,'Shary Bobbins',null,null,null,false,true,false,false,'adult','nanny',false,'yellow','brown',false,false,false,true,false,'sane',false,false,'hat'),
(18,'Maude Flanders',null,null,null,false,true,false,false,'adult','wife',false,'yellow','orange',true,false,false,true,true,'sane',false,false,null),
(19,'Jessica Lovejoy',null,null,null,false,true,true,false,'young','student',false,'yellow','black',false,false,false,true,false,'smart',false,false,'bow'),
(20,'Greta Wolfcastle',null,null,null,false,true,true,false,'young','student',false,'yellow','blonde',false,false,false,false,false,'sane',false,false,null),
(21,'Ling Bouvier',null,null,null,false,true,true,true,'young',null,false,'white','black',false,false,false,false,false,'sane',false,false,'bow'),
(22,'Maggie Simpson',null,null,null,false,true,true,true,'young',null,false,'yellow','yellow',false,false,false,true,false,'smart',false,false,'bow'),
(23,'Lisa Simpson',null,null,null,false,true,true,true,'young','student',false,'yellow','yellow',false,false,false,true,false,'smart',false,false,'necklace'),
(24,'Kodos',null,null,null,false,false,true,false,'adult',null,true,'green','bald',false,false,false,false,false,'evil',false,true,null),
(25,'Schneeball 2',null,null,null,false,false,true,true,'young',null,false,'dark','black',false,false,false,false,false,'lazy',false,false,null),
(26,'Jeff Albertson','Comic book guy',null,null,true,true,true,false,'adult','retailer',false,'yellow','brown',false,false,false,true,false,'sarcastic',true,true,null),
(27,'Barry Duffman','Duffman',null,null,true,true,true,false,'adult','mascot',true,'yellow','blonde',false,false,true,false,true,'athletic',false,false,'glasses'),
(28,'Rex Banner',null,null,null,true,true,false,false,'adult','police',true,'yellow','brown',false,false,false,true,false,'serious',false,false,'hat'),
(29,'Jasper Beardley',null,null,null,true,true,true,false,'old','pensioner',false,'yellow','bald',true,false,false,true,false,'sane',false,true,'beard'),
(30,'Clancy Bouvier',null,null,null,true,true,false,true,'adult','flightattendant',false,'yellow','brown',false,true,false,true,true,'sane',false,true,null),
(31,'Kent Brockman',null,null,null,true,true,true,false,'adult','tv',true,'yellow','white',true,true,false,true,true,'opportunism',false,true,null),
(32,'Charles Montgomery Burns',null,null,null,true,true,true,false,'old','akw',true,'yellow','grey',false,false,false,true,false,'evil',false,false,null),
(33,'Carl Carlson',null,null,null,true,true,true,false,'adult','akw',false,'dark','black',false,false,true,false,false,'silent',true,false,null),
(34,'Gary Chalmers',null,null,null,true,true,true,false,'old','school',true,'yellow','grey',false,false,false,true,false,'sane',false,false,'wig'),
(35,'Pedro Chespirito','Bienenmann',null,null,true,true,true,false,'adult','tv',true,'dark','brown',false,false,false,false,false,'democrat',false,true,'hat'),
(36,'Ned Flanders',null,null,null,true,true,true,false,'adult','church',false,'yellow','brown',true,false,false,true,true,'overprotective',false,false,'glasses'),
(37,'Lothar Folkman','Luigi Risotto',null,null,true,true,true,false,'adult','restaurant',false,'yellow','grey',false,false,false,false,false,'sane',false,true,'hat'),
(38,'John Frink Junior',null,null,null,true,true,true,false,'adult','scientist',true,'yellow','brown',false,false,false,true,true,'crazy',true,false,'glasses'),
(39,'Frank Grimes',null,null,null,true,true,false,false,'adult','akw',false,'yellow','black',false,false,false,true,false,'evil',false,false,'glasses'),
(40,'Matt Groening',null,null,null,true,true,true,false,'adult','tv',true,'yellow','grey',false,false,false,true,false,'sane',false,true,'glasses'),
(41,'Barney Gumble',null,null,null,true,true,true,false,'adult','retailer',false,'yellow','brown',false,false,false,false,true,'alcoholic',true,true,null),
(42,'Gil Gunderson',null,null,null,true,true,false,false,'adult','retailer',false,'yellow','grey',false,false,false,true,false,'failure',false,false,null),
(43,'Herman Hermann',null,null,null,true,true,true,false,'adult','retailer',false,'yellow','red',false,true,false,false,false,'crazy',false,false,null),
(44,'Julius Hibbert',null,null,null,true,true,true,false,'adult','doctor',true,'dark','black',false,false,false,true,true,'sane',false,true,null),
(45,'Herschel Krustofski','Krusty',null,null,true,true,true,false,'old','tv',true,'white','green',false,true,false,false,false,'grumpy',false,true,null),
(46,'Chester J. Lampwick',null,null,null,true,true,true,false,'old','tv',true,'yellow','grey',false,false,false,true,false,'sane',false,false,'hat'),
(47,'Dewey Largo',null,null,null,true,true,true,false,'adult','school',false,'yellow','grey',false,false,false,true,false,'sane',false,true,null),
(48,'Lenny Leonard',null,null,null,true,true,true,false,'adult','akw',false,'yellow','brown',false,true,false,true,false,'sane',true,false,null),
(49,'Timothy Lovejoy',null,null,null,true,true,true,false,'adult','church',true,'yellow','black',true,false,false,true,true,'stingy',false,false,null),
(50,'William MacMoran',null,null,null,true,true,true,false,'adult','school',false,'yellow','red',false,false,false,false,false,'athletic',false,false,'beard'),
(51,'Otto Mann',null,null,null,true,true,true,false,'adult','school',false,'yellow','black',false,true,true,true,false,'cool',false,false,'hat'),
(52,'Herbert Powell','Herb',null,null,true,true,true,true,'adult','retailer',true,'yellow','brown',false,true,false,true,false,'sane',false,true,null),
(53,'Horatio McCallister',null,null,null,true,true,true,false,'old','restaurant',false,'yellow','grey',false,true,false,true,true,'honest',false,true,'hat'),
(54,'Ralph Melish','Hans Maulwurf',null,null,true,true,true,false,'old','pensioner',false,'yellow','bald',false,false,false,true,false,'sane',false,true,'glasses'),
(55,'Apu Nahasapeemapetilon',null,null,null,true,true,true,false,'adult','retailer',false,'dark','black',false,false,false,false,true,'honest',true,false,'wig'),
(56,'Sanjay Nahasapeemapetilon',null,null,null,true,true,true,false,'adult',null,false,'dark','black',false,false,false,false,false,'sane',false,false,null),
(57,'Tom O''Flanagan',null,null,null,true,true,true,false,'old','bar',false,'yellow','grey',false,false,false,false,false,'sane',false,false,null),
(58,'Arnold Pye',null,null,null,true,true,true,false,'adult','tv',true,'yellow','brown',false,false,false,true,false,'sane',false,false,'glasses'),
(59,'Joseph Quimby','Joe',null,null,true,true,true,false,'young','major',true,'yellow','brown',false,false,false,true,true,'corrupt',false,true,null),
(60,'Nick Riviera','Dr. Nick',null,null,true,true,true,false,'adult','doctor',true,'yellow','black',false,false,false,true,false,'corrupt',false,false,'beard'),
(61,'Hank Scorpio',null,null,null,true,true,true,false,'adult','criminal',true,'yellow','brown',false,true,false,true,false,'evil',false,false,'beard'),
(62,'Abraham Simpson',null,null,null,true,true,true,true,'old','pensioner',false,'yellow','yellow',false,false,false,true,true,'crazy',false,true,'glasses'),
(63,'Homer Simpson',null,null,null,true,true,true,true,'adult','akw',false,'yellow','bald',false,false,false,true,true,'dumb',true,true,null),
(64,'Seymour Skinner',null,null,null,true,true,true,false,'adult','school',true,'yellow','grey',false,false,false,true,false,'sane',true,false,null),
(65,'Waylon Smithers',null,null,null,true,true,true,false,'adult','akw',false,'yellow','grey',false,false,true,true,false,'exactly',false,false,'glasses'),
(66,'Roy Snyder',null,null,null,true,true,true,false,'adult','police',true,'dark','black',false,false,false,true,false,'sane',false,true,'beard'),
(67,'Cletus Spuckler',null,null,null,true,true,true,false,'adult','farmer',false,'yellow','brown',false,false,false,true,true,'dumb',false,false,null),
(68,'Moe Szyslak',null,null,null,true,true,true,false,'adult','bar',true,'yellow','grey',false,false,false,true,false,'grumpy',false,false,null),
(69,'Drederick Tatum',null,null,null,true,true,true,false,'adult','sport',true,'dark','black',false,false,false,true,false,'evil',false,true,null),
(70,'Cecile Terwilliger',null,null,null,true,true,true,false,'adult','scientist',false,'yellow','brown',false,false,false,false,false,'evil',false,false,null),
(71,'Robert Terwilliger','Tingeltangel Bob',null,null,true,true,true,false,'adult','criminal',true,'yellow','red',false,false,false,false,false,'evil',false,false,null),
(72,'Rich Texan',null,null,null,true,true,true,false,'old','retailer',true,'yellow','grey',false,true,false,true,false,'republican',false,true,'hat'),
(73,'Chester Turley','Snake',null,null,true,true,true,false,'adult','criminal',true,'yellow','brown',false,false,false,true,false,'evil',false,false,null),
(74,'Melvin van Horne',null,null,null,true,true,true,false,'adult','tv',true,'yellow','blue',true,false,false,true,true,'conceited ',false,false,'bone'),
(75,'Kirk van Houten',null,null,null,true,true,true,false,'adult','unemployed',false,'yellow','blue',false,false,false,true,false,'failure',false,true,'glasses'),
(76,'Clancy Wiggum',null,null,null,true,true,true,false,'adult','police',true,'yellow','brown',false,true,false,true,true,'corrupt',false,true,'hat'),
(77,'Anthony D''Amico','Fat Tony',null,null,true,true,false,false,'adult','criminal',true,'yellow','grey',false,true,false,false,true,'evil',false,true,null),
(78,'Rainier Wolfcastle',null,null,null,true,true,true,false,'adult','tv',true,'yellow','brown',false,false,false,false,false,'athletic',false,false,null),
(79,'Artie Ziff',null,null,null,true,true,true,false,'adult','retailer',false,'yellow','black',false,false,false,true,false,'conceited ',false,false,'glasses'),
(80,'Larry Burns',null,null,null,true,true,true,false,'adult','retailer',false,'yellow','white',false,false,false,true,true,'lazy',false,true,null),
(81,'Freddy Quimby',null,null,null,true,true,true,false,'young','press',false,'yellow','brown',false,false,false,true,false,'evil',false,false,null),
(82,'Kinder der Fam. Nahasapeemapetilon',null,null,null,true,true,true,false,'young',null,false,'dark','black',false,false,false,false,false,'sane',false,false,null),
(83,'Kinder der Fam. Nahasapeemapetilon',null,null,null,false,true,true,false,'young',null,false,'dark','black',false,false,false,false,false,'sane',false,false,null),
(84,'Kinder der Fam. Spuckler',null,null,null,true,true,true,false,'young',null,false,'yellow','orange',false,false,false,true,false,'sane',false,false,null),
(85,'Kinder der Fam. Spuckler',null,null,null,false,true,true,false,'young',null,false,'yellow','orange',false,false,false,true,false,'sane',false,false,null),
(86,'Jeremy Peterson',null,null,null,true,true,true,false,'young','assistent',false,'yellow','brown',false,false,false,true,false,'dumb',false,false,null),
(87,'Gino Terwilliger',null,null,null,true,true,true,false,'young',null,false,'yellow','red',false,false,false,false,false,'evil',false,false,null),
(88,'Bart Simpson',null,null,null,true,true,true,true,'young','student',false,'yellow','yellow',false,false,false,true,false,'bold',true,false,null),
(89,'Ralph Wiggum',null,null,null,true,true,true,false,'young','student',false,'yellow','black',false,false,false,true,false,'dumb',false,true,null),
(90,'Kearney Zzyzwicz',null,null,null,true,true,true,false,'young','student',false,'yellow','bald',false,true,false,false,false,'evil',false,true,null),
(91,'Jimbo Jones',null,null,null,true,true,true,false,'young','student',false,'yellow','brown',true,true,false,true,false,'evil',false,false,'hat'),
(92,'Nelson Muntz',null,null,null,true,true,true,false,'young','student',false,'yellow','brown',false,true,false,true,false,'evil',false,true,null),
(93,'Rod Flanders',null,null,null,true,true,true,false,'young','student',false,'yellow','red',true,false,false,true,false,'overprotective',false,false,null),
(94,'Todd Flanders',null,null,null,true,true,true,false,'young','student',false,'yellow','brown',true,false,false,true,false,'overprotective',false,false,null),
(95,'Martin Prince',null,null,null,true,true,true,false,'young','student',false,'yellow','brown',false,false,false,true,false,'smart',false,true,null),
(96,'Dolphin Starbeam','Dolph',null,null,true,true,true,false,'young','student',false,'yellow','brown',false,false,false,true,false,'evil',false,false,null),
(97,'Milhouse van Houten',null,null,null,true,true,true,false,'young','student',false,'yellow','blue',false,false,false,true,false,'irritating',false,false,'glasses'),
(98,'Itchy',null,null,null,true,false,true,false,'old','tv',true,'blue','blue',false,false,false,true,false,'evil',false,false,null),
(99,'Joseph Teeny','Mr. Teeny',null,null,true,false,true,false,'adult','tv',true,'brown','brown',false,true,false,true,false,'bold',false,false,'hat'),
(100,'Scratchy',null,null,null,true,false,true,false,'old','tv',true,'black','black',false,false,false,true,false,'victim',false,false,null),
(101,'Knecht Ruprecht',null,null,null,true,false,true,true,'adult',null,false,'brown','brown',false,false,false,true,false,'loyal',false,false,null),
(102,'Kang',null,null,null,true,false,true,false,'adult',null,true,'green','bald',false,false,false,false,false,'evil',false,true,null)